### ISSUE TITLE
Cassandra Read Performance

### ISSUE THREAD

**Issue by vsonone** [pyr/cyanite#106]
Does the size of data list affect the performance in graphite ?

I have the following rollup:
"10s:24h"
"1m:30d"
"15m:1year"

Now lets say, if a datapoint comes every second to cyanite, then in 24 hours, the following rows will be created:

For "10s:24h" rollup
    (24*60*60/10 = 8640) rows will be created each row having 10 elements in the data list

For "1m:30d" rollup
    (24*60 = 1440) rows will be created each row having 60 elements in the data list

for "15m:1year" rollup
    (24*60*60/900 = 96 rows will be created with each row having 900 elements in the data list.

Is the above information correct. If yes then lets extrapolate this to store 90 days of data. Now the issue is that the time taken to query cyanite (using Grafana) to get 90 days of data for a given metric is more than the time required to query 1 day of data for the given metric. 
If you notice the # of rows returned by cassandra for both the query will be 8640. The only difference is the # of elements in each row, which will be more for 90 days data.

Also if I run a performance test with 10 users accessing 90 days of data simultaneously, then I start seeing cassandra timeouts in the backend, and it spends a lot of time in Garbage collection, but the same does not happen when I do the same by querying 1 day of data.

So I am concluding that the number of elements in the data list is affecting performance. Is there a way to limit that, or to avoid storing every element in each rollup. Can we not aggregate it before storing ?

Are you seeing similar performance issues in your cyanite/cassandra stack....?

**Comment by vsonone** [comment]
Can we not modify cyanite to store averages of the data points in a row, instead of storing every data points in every retention period ? It is making the read on cassandra slow, because of frequent GC because of large size of the data list.

**Comment by pyr** [comment]
@vsonone this is now the case in #80, I'd love help with testing!

**Comment by tjamesturner** [comment]
i am not sure this strategy will work.  specifically because when cyanite is run in a clustered environment, no single cyanite instance will know about all the input data. therefore the averages each instance stores should be weighted by the amount of traffic it receives. unfortunately, what i suspect will actually happen is that the average from each instance will be weighted equally when producing a final value to display in graphite since the correct weights are not stored in the record.

on my project we have a background task to pre-aggregate longer retention periods after cyanite is done writing to them.  generally we wait for either a later bucket to appear or a generous grace period to elapse (e.g. 5 minutes) before assuming that a bucket is complete and cyanite (carbon-c-relay) will not be writing to it any longer.

so, for example, if you were to receive the following data points in four consecutive minutes: [1,2,3,4], then the mean should be 2.5.  unfortunately, if [1,2,3] goes to one instance and [4] goes to another, then the averages stored in the db will be 2 and 4. so when cyanite goes to read the data back for graphite, it will return an average of 3, which is incorrect.

perhaps i am missing something?

**Comment by pyr** [comment]
Hi @tjamesturner. This is true and mentioned in the updated docs at http://cyanite.io.
However, it is trivial to ensure that points for a specific metric are routed to a single cyanite host.

I will also provide to alternative ways to make this even easier:

- A proxy inside cyanite itself, provided its configuration contains the topology
- Queue based inputs (Kafka & RabbitMQ)
