### ISSUE TITLE
Write problems in latest master

### ISSUE THREAD

**Issue by altvnk** [pyr/cyanite#193]
Here is an screenshot of metric data rendered with Grafana. On the left side of graphs is the latest version of cyanite, on the right side version from 31.01.16 (f1ec70e). Both are running with same config, same load (4 collectd hosts with few plugins enabled) and the same Cassandra cluster. You can clearly see that cyanite cannot handle even such small load and drops messages. The older one works just fine up to 40 hosts (~20k writes into cassandra).
![unspecified](https://cloud.githubusercontent.com/assets/3112142/13061144/a95889ac-d43e-11e5-9ecd-d8b845c64af5.png)

**Comment by altvnk** [comment]
PS: on the left side 4 instances of cyanite is running (with one picture is even worse). On the right side only one )

**Comment by ifesdjeen** [comment]
Looking into that one. Weird, my perf benchmarks were showing the opposite...

**Comment by ifesdjeen** [comment]
@altvnk we just recently reworked to use ring buffer disruptor (starting here 66b2f171834420c7c52a9d0b685be91d75531e67). I've done some performance tests, but we'll need some more extensive testing. 

We'll be reworking scheduling mechanism over the next few days. Currently I can only say that ingestion performance improved significantly, and writes are handled quite differently and with timer instead of the second queue, so at least that should not result into gaps. 

I'll keep that one around as a reminder to do extensive performance testing, but hopefully we have that issue more or less handled.

**Comment by altvnk** [comment]
Ok, thanks.

**Comment by ifesdjeen** [comment]
According to latest stress-tests this one is resolved
