### ISSUE TITLE
cassandra schema has a limit of 2 billion timestamps per path

### ISSUE THREAD

**Issue by mabrek** [pyr/cyanite#74]
See http://wiki.apache.org/cassandra/CassandraLimitations
For a single path it means ~60 years of  data with 1 second resolution but not so much for millisecond resolution data.
Slide 39 of http://www.slideshare.net/patrickmcfadin/cassandra-20-and-timeseries recommends to include date into partition key.

**Comment by pyr** [comment]
Hi @mabrek,

Keeping this in mind, I don't inted to change the schema dramatically since ms resolution is not the target for
cyanite's usage.

I do intend to provide a bit more leeway in how the schema gets constructed later on.

Mentioning this in the documentation (available in the feature/udpated-core branch) would be nice though if you're up for providing a PR
