### ISSUE TITLE
too much cpu used by hitting elasticsearch for every metric update

### ISSUE THREAD

**Issue by mabrek** [pyr/cyanite#96]
When I'm sending ~600 metrics every second (just a single host with collectd and 1s update interval) cyanite jvm consumes about 30% of a single core + es jvm consumes another 30%. It looks like every time metric arrives to cyanite it issues a request to es which is not really needed (same set of metrics is being reported every second).

**Comment by mabrek** [comment]
One possible solution is to maintain a set of hashes of all indexed paths in memory and check it before sending candidate path to ES.
md5 hashes of 1M paths would take only 16Mb (and some data structure overhead) but it will decrease CPU usage significantly.

**Comment by EinsamHauer** [comment]
Anton, 

16 Mb is quite underestimated in fact - there will be  quite some overhead (arrays, hashtables, pointers, etc). But the idea itself is viable. In fact I became somehow desperate about these performance issues and ended up with implementing my own writer to C* (with ~ same functionality as cyanite) with expiring paths cache. Probably, mostly because I'm not clever enough to master clojure:-)

**Comment by jippi** [comment]
bump bump

**Comment by pyr** [comment]
Hi everyone. I expect to tackle this mid-july, sorrya bout the delay :-(

**Comment by ebpitts** [comment]
@EinsamHauer I assume you're referring to https://github.com/EinsamHauer/disthene ?

**Comment by pyr** [comment]
I just started gettings things in good shape to have a nicer core with rollup capacity. Again sorry for the wait everyone.

**Comment by EinsamHauer** [comment]
@ebpitts yes, that's what we ended up using, at least for the time being

**Comment by pyr** [comment]
This problem is now addressed in #80, cheers!
