### ISSUE TITLE
ElasticSearch never returning results for graphite web

### ISSUE THREAD

**Issue by mwmanley** [pyr/cyanite#97]
I have a brand new Cyanite install (stock pull from here) with ES 1.5.  I see data populating into ES from Cyanite, but when using the Graphite web browser, it never returns any results for the top level of the tree.  I am using the REST interface to ES as defined in my cyanite.yaml:

index:
  use: "io.cyanite.es_path/es-rest"
  index: "cyanite_paths" #defaults to "cyanite_paths"
  url: "http://esearch01:9200" #defaults to http://localhost:9200
  chan_size: 1000 # defaults to 10000
  batch_size: 500 # defaults to 1000

I clearly see the data populating in ES with a curl:

curl "http://esearch01:9200/cyanite_paths/_search"
{"took":5,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1320,"max_score":1.0,"hits":[{"_index":"cyanite_paths","_type":"path","_id":"stg.nj1.bidder06.tap","_score":1.0,"_source":{"path":"stg.nj1.bidder06.tap","depth":4,"tenant":"","leaf":true}},{"_index":"cyanite_paths","_type":"path","_id":"stg.nj1.consumer-tracked01.clnt.counters.service_creation","_score":1.0 ...

but when the query hits ES, it returns no results:

ES query generated by Cyanite:
{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"depth":{"from":1,"to":1}}},{"term":{"tenant":""}},{"regexp":{"path":".*","_cache":true}}]}}}},"size":100}

Result set from ES, which shows no hits:
{"_scroll_id":"cXVlcnlUaGVuRmV0Y2g7NTsxMDM0OncySllmRVZEUkFxQTBDWDYzcnBKQkE7MTAzMzp3MkpZZkVWRFJBcUEwQ1g2M3JwSkJBOzEwMzE6dzJKWWZFVkRSQXFBMENYNjNycEpCQTsxMDMyOncySllmRVZEUkFxQTBDWDYzcnBKQkE7MTY4OkNZdE9MU0MzUlA2T1RpMHVfcmVYT3c7MDs=","took":11,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}

I don't see what I could be doing so wrong where it never returns the top level branches of the Graphite paths.  If I remove ES from the equation, I can use the Graphite web browser to navigate around, though I would *greatly* prefer to keep ES in the equation.

Has anyone see this issue before with path queries into ES?

**Comment by chjohnst** [comment]
Have you tried this on ES 1.4?  Wondering if something changed there.

**Comment by mwmanley** [comment]
I tried this on ES 1.3, 1.4, and 1.5.  I got the same results for all these, which is why I am puzzled.  Did you guys take any extra steps with ES other than a base install?

**Comment by mwmanley** [comment]
Update, ES 0.90.11 works perfectly.

**Comment by mwmanley** [comment]
For whatever reason, it works again with 1.5.  Closing this since it's not a bug, I guess.

**Comment by pauzed** [comment]
I just ran into this which puzzled me to no avail.  I had deleted my cyanite_paths index, and recreated it by hand, as I have dynamic index creation disabled.  I was able to see data in ELS, and able to query using GET, but when I used POST to search, I was getting empty results similar to you.  Finally, I dropped the index, enabled dynamic index creation, letting Cyanite post data to ES which would trigger an index creation, and then my ES paths began working as expected.

**Comment by TransactCharlie** [comment]
I had a similar issue and I *think* it is down to the mapping that are created during index creation. I've seen the mapping be different when cyanite cannot find any rows from when it works. - I'm not sure how the situation arises but I've switched to creating the elastic search index (and mapping) ahead of time using an ansible provisioning step before starting cyanite.

I've been building a stack in AWS and so I've been nuking the site from orbit *a lot* while testing things out. I was noticing that roughly 50% of the time I'd get a system that couldn't generate graphs. Since I switched to provisioning the Elasticsearch index ahead of time, I've had no problems

I'm hoping to open source my stack (cloud-formation and ansible playbooks) at some point but I'll have to discuss that with my company.

However, I don't see any issues with the actual elasticsearch part so here it is:

The unusable portion that actually makes the index. (ansible's uri action chokes on son btw so I'm using a curl)
```yaml
- name: Create Pathstore Index and mapping
  shell: "curl -X POST http://{{ dns_names.PathStoreDNS }}:9200/cloud_graphite_paths -H \"Content-Type: application/json\" --data-binary \"@/opt/cyanite/mappings/cloud_graphite_paths.index.json\""
  register: result
  until: result.stdout.find("acknowledged") != -1 or result.stdout.find("IndexAlreadyExistsException") != -1
  retries: 5
  delay: 10
  notify:
  - start_supervisord
```

and the contents of the mapping file (which I just extracted from the index one of the builds that did work correctly):
```son
{
  "settings" : {
    "number_of_shards" : 5,
    "replicas": 2
    },
  "mappings" : {
    "path": {
      "properties": {
        "depth": {"type": "long"},
        "leaf": {"type": "boolean"},
        "path": {
          "type": "string",
          "index": "not_analyzed"
          },
        "tenant": {
          "type": "string",
          "index": "not_analyzed"
          }
      }
    }
  }
}
```
(obviously your shards and replication policy might be different). I don't have an example of the mapping from a run that didn't work but it definitely didn't have the `"not_analyzed"` tokens in it.

Hope that might help - and possibly someone more familiar with the code might be able to confirm or deny my hypothesis.
